version: "3.3"

services:

  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"

    environment:
      # comment below line to set it to default ERROR
      - TRAEFIK_LOG_LEVEL = DEBUG

      - TRAEFIK_ENTRYPOINTS_websecure = true
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS = ":443"
      - TRAEFIK_ENTRYPOINTS_web = true
      - TRAEFIK_ENTRYPOINTS_web_ADDRESS = ":80"

      #- TRAEFIK_API = true
      #- TRAEFIK_API_DEBUG = true
      #- TRAEFIK_API_INSECURE = true

      - TRAEFIK_PROVIDERS_DOCKER = true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT = false

      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_TLSCHALLENGE = true
      # remove below line to enable letsencrypt
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_CASERVER = https://acme-staging-v02.api.letsencrypt.org/directory"
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_EMAIL = kenevist@gmail.com
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_STORAGE = /letsencrypt/acme.json

 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      #- "traefik.http.routers.traefik.middlewares=authtraefik"
      #- "traefik.http.middlewares.authtraefik.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/" # user/password

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"


  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.kenevist.ir`)"

      # not needed? - "traefik.enable=true"
      
